version: '3'

services:
  corewebapi:
    image: nileshgule/corewebapi
    build:
      context: ./CoreWebAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - coremvc
    networks:
      - webnet
  coremvc:
    image: nileshgule/coremvc
    build:
      context: ./CoreMVC
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet: