version: '3'

services:
  
  corewebapi:
    image: corewebapi
    build:
      context: ./CoreWebAPI
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  coremvc:
    image: coremvc
    build:
      context: ./CoreMVC
      dockerfile: Dockerfile
    depends_on: 
      - corewebapi
    ports:
      - "80:80"
