---
- hosts: localhost
  gather_facts: no
  tasks:

  - name: Run docker compose build command
    shell: docker-compose -f docker-compose-build.yml build

  - name: Run docker compose up command
    shell: docker-compose -f docker-compose-build.yml up

  - name: Run docker ps command showing all services
    shell: docker ps