version: '3'

services:
  
  coremvc:
    image: nileshgule/coremvc
    depends_on: 
      - corewebapi
    ports:
      - "80:80"
  
  corewebapi:
    image: nileshgule/corewebapi
    ports:
      - "8090:80"

  
