apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coremvc-ingress
  namespace: my-project
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: coremvc.example.local
    http:
      paths:
      - path: /
        backend:
          serviceName: coremvc
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: corewebapi-ingress
  namespace: my-project
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: corewebapi.example.local
    http:
      paths:
      - path: /api/keyvalue
        backend:
          serviceName: corewebapi
          servicePort: 80
