---
kind: Service
apiVersion: v1
metadata:
  name: coremvc
  namespace: my-project
  labels:
    run: coremvc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    run: coremvc
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: corewebapi
  namespace: my-project
  labels:
    run: corewebapi
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31001
  selector:
    run: corewebapi
  type: NodePort
