---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coremvc
  # namespace: my-project
  labels:
    run: coremvc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: coremvc
  template:
    metadata:
      labels:
        run: coremvc
        app: coremvc
    spec:
      containers:
      - name: coremvc
        image: nileshgule/coremvc
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: corewebapi
  # namespace: my-project
  labels:
    run: corewebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: corewebapi
  template:
    metadata:
      labels:
        run: corewebapi
    spec:
      containers:
      - name: corewebapi
        image: nileshgule/corewebapi
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: coremvc
#   # namespace: my-project
#   labels:
#     run: coremvc
# spec:
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80
#     nodePort: 31000
#   selector:
#     run: coremvc
#   type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: corewebapi
  # namespace: my-project
  labels:
    run: corewebapi
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31001
  selector:
    run: corewebapi
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: coremvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: coremvc

---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
     name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sql2017
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sql2017
        image: nileshgule/sqldb
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data

---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: sql2017
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer