---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coremvc
  # namespace: my-project
  labels:
    run: coremvc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: coremvc
  template:
    metadata:
      labels:
        run: coremvc
    spec:
      containers:
      - name: coremvc
        image: nileshgule/coremvc
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: corewebapi
  # namespace: my-project
  labels:
    run: corewebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: corewebapi
  template:
    metadata:
      labels:
        run: corewebapi
    spec:
      containers:
      - name: corewebapi
        image: nileshgule/corewebapi
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: coremvc
#   # namespace: my-project
#   labels:
#     run: coremvc
# spec:
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80
#     nodePort: 31000
#   selector:
#     run: coremvc
#   type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: corewebapi
  # namespace: my-project
  labels:
    run: corewebapi
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31001
  selector:
    run: corewebapi
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: coremvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: coremvc